// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3ZckPePTwk3-Rl4ibS2fO69Ml9d6FD8U',
    appId: '1:766273050007:web:0cb0b5a53fa5eb53ed60d2',
    messagingSenderId: '766273050007',
    projectId: 'memo-moviles',
    authDomain: 'memo-moviles.firebaseapp.com',
    storageBucket: 'memo-moviles.firebasestorage.app',
    measurementId: 'G-QD0XP15KGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi1ehRUWGkFAAKKPL2OtxyFpi6Zatkt1U',
    appId: '1:766273050007:android:97c275960c85f4ebed60d2',
    messagingSenderId: '766273050007',
    projectId: 'memo-moviles',
    storageBucket: 'memo-moviles.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG9yo_k8G1fRQyaWHlLWVPU3on31BiioA',
    appId: '1:766273050007:ios:0eef838293b3aa73ed60d2',
    messagingSenderId: '766273050007',
    projectId: 'memo-moviles',
    storageBucket: 'memo-moviles.firebasestorage.app',
    iosBundleId: 'com.example.practicas',
  );
}
